Repository AdamsLair/duality-docs, pull requests merged in 2018-03, with the labels that each got.

#15 Added Gemfile, Config, GitIgnore for Local Setup
  .gitignore
  Gemfile
  Gemfile.lock
  _config.yml
Labels: Docs, Task

#18 Added Issue and Pull Request Templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Docs, Improvement

#19 Added a README.md File
  README.md
Labels: Docs, Task

#21 Improved Code Readability
  assets/css/style.scss
Labels: Docs, Improvement

#20 Cleanup Pages to Fix Images, Links, Remove HTML
  pages/img/CreatingBulletLikeObjects/BulletOneDrag.png
  pages/img/CreatingBulletLikeObjects/BulletOneInitialComponents.png
  pages/img/CreatingBulletLikeObjects/BulletRigidbodyEdit.png
  pages/img/CreatingBulletLikeObjects/PrefabApply.png
  pages/img/CreatingBulletLikeObjects/PrefabContextMenu.png
  pages/img/CreatingBulletLikeObjects/SceneViewWithEnemy.png
  pages/img/CreatingBulletLikeObjects/SettingBulletPrefab.png
  pages/img/CreatingBulletLikeObjects/bulletOne.png
  pages/v2/Components-and-Basic-ICmpInterfaces.md
  pages/v2/Creating-Bullet-like-Objects.md
  pages/v2/Custom-Renderers.md
  pages/v2/Development-Cycle.md
  pages/v2/Duality-and-Version-Control.md
  pages/v2/Framework-Structure.md
  pages/v2/GameObject.md
  pages/v2/Guidelines/Best-Practices.md
  pages/v2/Handling-Object-Data.md
  pages/v2/Input-Handling.md
  pages/v2/Library-Usage.md
  pages/v2/Project-Version-History.md
  pages/v2/Resource.md
  pages/v2/Tilemaps.md
  pages/v2/Working-With-Animations.md
  pages/v2/getting-started.md
  pages/v3/Project-Version-History.md
Labels: Cleanup, Docs, Error

#22 Added a Markdown Table of Contents to All Article Pages
  .gitignore
  Gemfile.lock
  pages/v2/Branch-Descriptions.md
  pages/v2/Choosing-Duality.md
  pages/v2/Components-and-Basic-ICmpInterfaces.md
  pages/v2/Creating-Bullet-like-Objects.md
  pages/v2/Custom-Renderers.md
  pages/v2/Development-Cycle.md
  pages/v2/Duality-and-Version-Control.md
  pages/v2/Framework-Structure.md
  pages/v2/GameObject.md
  pages/v2/Guidelines/Best-Practices.md
  pages/v2/Guidelines/Common-Pitfalls.md
  pages/v2/Handling-Object-Data.md
  pages/v2/Input-Handling.md
  pages/v2/Library-Usage.md
  pages/v2/Package-Management.md
  pages/v2/Resource.md
  pages/v2/Tilemaps.md
  pages/v2/Working-With-Animations.md
  pages/v2/how-to-contribute.md
Labels: Docs, Improvement
